# netlify.toml (place at the repo root)

[[headers]]
for = "/*"
  [headers.values]
  Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
  X-Frame-Options           = "SAMEORIGIN"
  X-Content-Type-Options    = "nosniff"
  Referrer-Policy           = "strict-origin-when-cross-origin"
  Permissions-Policy        = "camera=(), microphone=(), geolocation=()"
  # Conservative CSP that works with your site (HTML/CSS/SVG, inline CSS ok)
  Content-Security-Policy   = "default-src 'self'; img-src 'self' data: https:; font-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; script-src 'self' 'unsafe-inline'; frame-ancestors 'self'; upgrade-insecure-requests"
